dist: xenial
language: elixir
install: true
sudo: true
before_install:
  - docker run --detach --rm --hostname bugs-bunny --name roger_rabbit -p 5672 rabbitmq:3.7.7
  - export POLLER_RMQ_PORT=$(docker inspect --format '{{ (index (index .NetworkSettings.Ports "5672/tcp") 0).HostPort }}' roger_rabbit )
  - until curl --silent -XGET --fail http://127.0.0.1:${POLLER_RMQ_PORT} &> /dev/null ; do printf '.'; sleep 1; done
elixir:
  - "1.8"
before_script:
  - "epmd -daemon"
  - "mix local.hex --force"
  - "mix local.rebar --force"
  - "mix deps.get"
  - "mix compile"
after_success:
  - MIX_ENV=test mix coveralls.travis
script:
  - "mix test"
otp_release:
  - "21.0.9"
cache:
  directories:
    - _build
    - deps
services:
  - docker
